# Documentation at http://goreleaser.com
project_name: skprmail

builds:
  - binary: skprmail
    env: [ CGO_ENABLED=0 ]
    goos: [ linux, darwin ]
    goarch: [ amd64, arm64 ]

archives:
  - replacements:
      darwin: macOS
    format: binary

nfpms:
  - formats: [ apk ]
    apk:
      signature:
        key_name: skpr
        key_file: keys/skpr.rsa.priv
release:
  prerelease: auto
  github:
    owner: skpr
    name: mail
