# Documentation at http://goreleaser.com
project_name: skprmail

builds:
  - binary: skprmail
    env: [ CGO_ENABLED=0 ]
    goos: [ linux, darwin ]
    goarch: [ amd64, arm64 ]
    ldflags: '-extldflags "-static"'

archives:
  - replacements:
      darwin: macOS
    format: binary

nfpms:
  - description: A drop-in replacement for Sendmail which sends email via Amazon SES.
    homepage: https://github.com/skpr/mail
    formats: [ apk ]

release:
  prerelease: auto
  github:
    owner: skpr
    name: mail
