version: 2.1

workflows:
  test:
    jobs:
      - lint
      - unit

jobs:
  lint:
    docker:
      - image: golang:1.14
    working_directory: /go/src/github.com/skpr/mail
    steps:
      - checkout
      - run: |
          go get golang.org/x/lint/golint
          make lint

  unit:
    docker:
      - image: golang:1.13
    working_directory: /go/src/github.com/skpr/mail
    steps:
      - checkout
      - run: make test
